apiVersion: v1
kind: Namespace
metadata:
  name: echoserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: bodnar1212/k8s:latest
          imagePullPolicy: Always
          name: echoserver
          ports:
            - containerPort: 80
        - image: tomcat:latest
          imagePullPolicy: Always
          name: echoserver2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - name: test-web-app-listener
      protocol: TCP
      port: 80
      targetPort: 80
    - name: test-web-2-app-listener
      protocol: TCP
      port: 8888
      targetPort: 8080
  type: NodePort
  selector:
    app: echoserver